#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    Originlocation:
      type: object
      required: true
      properties:
        locationcode:
          type: string
          required: true
          example: "MUB-IND"
    DistinationLocation:
      type: object
      required: true
      properties:
        locationcode:
          type: string
          required: true
          example: "KLG-MY" 