#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    Availableseats:
      type: number
      required: true
      example: 20
    DeparturedateTime:
      type: string
      required: true
      example: "2019-04-10T16:41:41.090z"
    Travelroute:
      type: object
      required: true
      properties:
        distinationlocation:
          type: object
          properties:
            Locationcode:
              type: string
              required: true
              example: "KLY-MY"
            originlocation:
                type: string
                required: true
                example: "MUB-IND" 