#%RAML 1.0 Library
usage:
traits:
  Transaction_id: !include /Libarary/Common/traits/Headers-Routes-Schdeules-trait.raml
  queryParameters: !include /Libarary/Common/traits/QueryParameter-Schedule-trait.raml