#%RAML 1.0
title: SYSTEM_API-TravelOnTip
description: This raml will fetch routes & schedules from TravelOntip system Api.

uses:
  common: /Libarary/Common/Common-Traits/Common-Traits-library.raml

types:
  Routes-response-dataType: !include /Libarary/Routes/DataType/Route-Response-dataType.raml
  Schdeules-response-datatype: !include /Libarary/Schedules/DataType/Schdeule-Response-dataType.raml
  400-responsecode: !include /Libarary/Common/DataType/400-responsecode-dataType.raml
  404-responsecode: !include /Libarary/Common/DataType/404-responsecode-dataType.raml
  500-responsecode: !include /Libarary/Common/DataType/500-responsecode-dataType.raml
/transportType:
  /transaportcompany:
    /Routes:
      get:
        is:
          - common.Transaction_id 
       
        responses:
          200:
            body:
              application/json:
                type: Routes-response-dataType 
                example: !include/Libarary/Routes/Example/Routes-Response-example.raml 
                        
          400:
           body:
             application/json:
               type: 400-responsecode
          404:
            body:
              application/json:
                type: 404-responsecode
          500:
            body:
              application/json:
                type: 500-responsecode
    
    /schedules:
      get:
        is:
          - common.Transaction_id 
          - common.queryParameters
        responses:
            200:
              body:
                application/json:
                  type: Schdeules-response-datatype
                  example: !include/Libarary/Schedules/Example/Schedules-Response-example.raml
            400:
             body:
              application/json:
                type: 400-responsecode
            404:
             body:
              application/json:
                type: 404-responsecode
            500:
             body:
                application/json:
                 type: 500-responsecode
